version: "3"

services:
  nginx-proxy:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/2022:/etc/nginx/ssl
    network_mode: host
    # ports:
    #   - 8080:80
    #   - 8443:443
    environment:
      TZ: Asia/Bangkok
